# Generated by Django 6.0.3 on 2026-03-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
