# Generated by Django 6.0.3 on 2026-05-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
